### ISSUE TITLE
Add option to group identical properties

### ISSUE THREAD

**Issue by jvatic** [jvatic/js-css#2]
``` css
#s0 {
    color: #000;
    text-align: center;
}
#s1 {
    color: #000;
}
```

becomes

``` css
#s0, #s1 {
    color: #000;
}
#s0 {
    text-align: center;
}
```
